version: "3"

services:
    joomla:
        image: enz93/joomla_img
        hostname: joomla
        environment:
         JUSERNAME: asd
         JUSEREMAIL: asd@localhost.com
         JUSERPASS: 1234
         DB: joomla
         DBUSER: joomla
         DBPASS: joomla123
         DBPREFIX: prfx_
         LIVE_SITE: http:\/\/joomla.local # escaped per evitare errori
         JOOMLA_DB_HOST: db
         MYSQL_ROOT_PASSWORD: secret
        ports: 
            - 8081:80
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                    - node.role == worker
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.joomla.rule=Host(`joomla.local`)"
                - "traefik.http.routers.joomla.priority=49"
                - "traefik.http.routers.joomla.entrypoints=web"
                - "traefik.http.services.joomla.loadbalancer.server.port=80"
        entrypoint: ["wait-for-it.sh", "-t", "120", "db:3306", "--", "docker-php-entrypoint", "-D FOREGROUND"] 
        depends_on:
            - db  
        volumes:
            - /GlusterFs/joomla/:/var/www/html/
        networks:
            - intnet   
        
    pmy:
        image: enz93/pmy_img
        hostname: pmy
        depends_on: 
           - db
        ports: 
            - 8082:80
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                    - node.role == worker
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.managedb.rule=Host(`managedb.joomla.local`)"
                - "traefik.http.routers.managedb.priority=50"
                - "traefik.http.routers.managedb.entrypoints=web"
                - "traefik.http.services.managedb.loadbalancer.server.port=80"
        environment:
            DB_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - /GlusterFs/phpmyadmin:/config
        networks:
            - intnet
    db:
        image: mariadb
        hostname: db
        ports:
           - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: joomla
            MYSQL_USER: joomla
            MYSQL_PASSWORD: joomla123
        volumes:
            - /GlusterFs/mysql:/var/lib/mysql
        networks:
            - intnet
    prometheus:
        image: prom/prometheus:latest
        depends_on: 
           - node-exporter
           - cadvisor
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/alert.rules:/etc/prometheus/alert.rules
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - '9090:9090'  
        deploy:
            placement:
                constraints:
                    - node.role == manager
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.prometheus.rule=Host(`prometheus.joomla.local`)"
                - "traefik.http.routers.prometheus.priority=50"
                - "traefik.http.routers.prometheus.entrypoints=web"
                - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
        networks:
            - intnet
    node-exporter:
        image: prom/node-exporter:latest
        volumes:       
            - /proc:/host/proc:ro       
            - /sys:/host/sys:ro       
            - /:/rootfs:ro       
        command:       
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points'
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - '9100:9100'
        deploy:       
            mode: global 
        networks:
            - intnet
    grafana:
        image: grafana/grafana:latest
        depends_on: 
           - prometheus
        volumes: 
            - /GlusterFs/grafana:/var/lib/grafana
            - /GlusterFs/grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_SERVER_DOMAIN=localhost:3000
            - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s
            - GF_USERS_ALLOW_SIGN_UP=false
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        deploy:
            placement:
                constraints:
                - node.role == manager
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.monitor.rule=Host(`monitor.joomla.local`)"
                - "traefik.http.routers.monitor.priority=50"
                - "traefik.http.routers.monitor.entrypoints=web"
                - "traefik.http.services.monitor.loadbalancer.server.port=3000"
        networks:
            - intnet
    cadvisor:
        image: google/cadvisor:latest
        volumes:
            - /:/rootfs:ro 
            - /var/run:/var/run:rw
            - /sys:/sys:ro 
            - /var/lib/docker/:/var/lib/docker:ro 
        ports:
            - 8084:8080
        deploy:
            mode: global
        networks:
            - intnet
    traefik:
        image: "traefik:v2.0.0-rc3"
        hostname: traefik
        command:
            - "--api=true"
            - "--api.debug=true"
            - "--api.insecure=true"
            - "--providers.docker.endpoint=unix:///var/run/docker.sock"
            - "--providers.docker.swarmMode=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=service_intnet"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        deploy:
            placement:
                constraints:
                    - node.role == manager
        networks: 
            - intnet
            - extnet
networks:
    intnet:
        internal: true
        ipam:
            config:
                - subnet: 192.168.200.0/24
    extnet:
        ipam:
            config:
                - subnet: 192.168.100.0/24
